openapi: 3.0.0
info:
  title: Admin Panel API
  description: Admin panel API for companies and employees
  version: 1.0.0

servers:
  - url: https://employee-companies-api.otar.redberryinternship.ge
    description: production server
  - url: http://localhost:3000/
    description: local server
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /login:
    post:
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              example:
                email: example@redberry.ge
                password: '12345'
              required:
                - email
                - password
      responses:
        '200':
          description: Successfully logged in
        '400':
          description: Wrong password or email
        '422':
          description: Invalid request body formation
  /companies:
    get:
      summary: Get all companies
      tags:
        - Company
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Company list fetched
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                    name:
                      type: string
                    websiteAddress:
                      type: string
                    logoAddress:
                      type: string
                    establishmentDate:
                      type: string
                  example:
                    _id: 111111111
                    name: Amazon
                    websiteAddress: https://amazon.com
                    logoAddress: https://www.amazon.com/ref=nav_logo
                    establishmentDate: 1994-07-05
                  required:
                    - name
                    - websiteAddress
                    - logoAddress
                    - establishmentDate
        '401':
          description: Not authorized
  /company:
    post:
      summary: Create company
      tags:
        - Company
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                websiteAddress:
                  type: string
                logoAddress:
                  type: string
                establishmentDate:
                  type: string
              example:
                name: Amazon
                websiteAddress: https://amazon.com
                logoAddress: https://www.amazon.com/ref=nav_logo
                establishmentDate: 1995-07-05
      responses:
        '201':
          description: Company created
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  name:
                    type: string
                  websiteAddress:
                    type: string
                  logoAddress:
                    type: string
                  establishmentDate:
                    type: string
        '401':
          description: Not authorized
        '400':
          description: Wrong company id
        '422':
          description: Invalid request body formation
  /company/{id}:
    get:
      summary: Get company by id
      tags:
        - Company
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Company ID
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Specific company fetched
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  name:
                    type: string
                  websiteAddress:
                    type: string
                  logoAddress:
                    type: string
                  establishmentDate:
                    type: string
                  employees:
                    type: array
                example:
                  _id: '111111111'
                  name: Amazon
                  websiteAddress: https://amazon.com
                  logoAddress: https://www.amazon.com/ref=nav_logo
                  establishmentDate: 1995-07-05
                  employees:
                    - _id: '1111111111'
                      company: '123456789'
                      name: Jeff
                      lastName: Bezos
                      startDate: 1994-07-05
                      birthDate: 1964-01-12
                      personalID: '1223334444'
                      jobPosition: CEO

        '401':
          description: Not authorized
        '400':
          description: Wrong company id
    put:
      summary: Update company by id
      tags:
        - Company
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Company ID
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                _id:
                  type: string
                name:
                  type: string
                websiteAddress:
                  type: string
                logoAddress:
                  type: string
                establishmentDate:
                  type: string
              example:
                name: Amazon
                websiteAddress: https://amazon.com
                logoAddress: https://www.amazon.com/ref=nav_logo
                establishmentDate: 1994-07-05
      responses:
        '200':
          description: Company updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  name:
                    type: string
                  websiteAddress:
                    type: string
                  logoAddress:
                    type: string
                  establishmentDate:
                    type: string
        '401':
          description: Not authorized
        '400':
          description: Wrong company id
        '422':
          description: Invalid request body formation
    delete:
      summary: Delete company by id
      tags:
        - Company
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Company ID
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Company deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
        '401':
          description: Not authorized
        '400':
          description: Wrong company id
  /employee:
    post:
      summary: Add employee
      tags:
        - Employee
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                company:
                  type: string
                name:
                  type: string
                lastName:
                  type: string
                startDate:
                  type: string
                birthDate:
                  type: string
                personalID:
                  type: string
                jobPosition:
                  type: string
              example:
                company: '123456789'
                name: Jeff
                lastName: Bezos
                startDate: 1994-07-05
                birthDate: 1964-01-12
                personalID: '1223334444'
                jobPosition: CEO
              required:
                - company
                - name
                - lastName
                - startDate
                - birthDate
                - personalID
                - jobPosition
      responses:
        '201':
          description: Employee added
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  lastName:
                    type: string
                  startDate:
                    type: string
                  birthDate:
                    type: string
                  personalID:
                    type: string
                  jobPosition:
                    type: string
        '400':
          description: Wrong company id in body
        '401':
          description: Not authorized
        '422':
          description: Invalid request body formation
  /employee/{id}:
    get:
      summary: Get employee by id
      tags:
        - Employee
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Employee ID
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Specific employee fetched
          content:
            application/json:
              schema:
                type: object
                properties:
                  company:
                    type: string
                  name:
                    type: string
                  lastName:
                    type: string
                  startDate:
                    type: string
                  birthDate:
                    type: string
                  personalID:
                    type: string
                  jobPosition:
                    type: string
                example:
                  company: '123456789'
                  name: Jeff
                  lastName: Bezos
                  startDate: 1994-07-05
                  birthDate: 1964-01-12
                  personalID: '1223334444'
                  jobPosition: CEO
        '401':
          description: Not authorized
        '400':
          description: Wrong employee id
    put:
      summary: Update employee by id
      tags:
        - Employee
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Employee ID
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                company:
                  type: string
                name:
                  type: string
                lastName:
                  type: string
                startDate:
                  type: string
                birthDate:
                  type: string
                personalID:
                  type: string
                jobPosition:
                  type: string
              example:
                name: Jeff
                lastName: Bezos
                startDate: 1994-07-05
                birthDate: 1964-01-12
                personalID: '1223334444'
                jobPosition: CEO
      responses:
        '201':
          description: Employee updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  lastName:
                    type: string
                  startDate:
                    type: string
                  birthDate:
                    type: string
                  personalID:
                    type: string
                  jobPosition:
                    type: string
        '401':
          description: Not authorized
        '400':
          description: Wrong employee id
        '422':
          description: Invalid request body formation
    delete:
      summary: Delete employee by id
      tags:
        - Employee
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Employee ID
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Employee deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string

        '401':
          description: Not authorized
        '400':
          description: Wrong employee id
